In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
arr = np.arange(0,9)
arr[:]=5

In [10]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(1)

array([0.95994301])

In [24]:
np.random.randn(25)

array([-0.2694537 , -1.7613231 ,  0.43897938, -0.74599175,  0.46823296,
       -0.89939864,  0.19954749,  2.04993053, -1.73471625, -0.27879268,
       -0.88939572, -1.27381648,  0.78745411,  0.02835973, -0.33919032,
       -1.41680413,  0.87671444, -0.15483033, -0.1123521 , -0.99976509,
       -1.16079712,  0.9321858 , -1.11484863, -1.25023616,  1.32915682])

In [33]:
np.linspace(0,0.9999,100).reshape(10,10)

array([[0.    , 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707,
        0.0808, 0.0909],
       [0.101 , 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919],
       [0.202 , 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626, 0.2727,
        0.2828, 0.2929],
       [0.303 , 0.3131, 0.3232, 0.3333, 0.3434, 0.3535, 0.3636, 0.3737,
        0.3838, 0.3939],
       [0.404 , 0.4141, 0.4242, 0.4343, 0.4444, 0.4545, 0.4646, 0.4747,
        0.4848, 0.4949],
       [0.505 , 0.5151, 0.5252, 0.5353, 0.5454, 0.5555, 0.5656, 0.5757,
        0.5858, 0.5959],
       [0.606 , 0.6161, 0.6262, 0.6363, 0.6464, 0.6565, 0.6666, 0.6767,
        0.6868, 0.6969],
       [0.707 , 0.7171, 0.7272, 0.7373, 0.7474, 0.7575, 0.7676, 0.7777,
        0.7878, 0.7979],
       [0.808 , 0.8181, 0.8282, 0.8383, 0.8484, 0.8585, 0.8686, 0.8787,
        0.8888, 0.8989],
       [0.909 , 0.9191, 0.9292, 0.9393, 0.9494, 0.9595, 0.9696, 0.9797,
        0.9898, 0.9999]])

In [35]:
np.linspace(0,1,20).reshape(4,5)

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [42]:
arr_2d = np.arange(1,26).reshape(5,5)

In [43]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr_2d[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [47]:
arr_2d[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [48]:
np.sum(arr_2d)

325

In [49]:
np.std(arr_2d)

7.211102550927978

In [50]:
arr_2d.sum(axis=0)

array([55, 60, 65, 70, 75])