In [1]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(mylist)

In [4]:
arr

array([1, 2, 3])

In [5]:
mymatrix = [[1,3,4],[2,5,7]]
mymatrix

[[1, 3, 4], [2, 5, 7]]

In [7]:
np.array(mymatrix)

array([[1, 3, 4],
       [2, 5, 7]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.98616715, 0.21921843, 0.31416002, 0.53992891, 0.84251806])

In [18]:
np.random.rand(5,5)

array([[0.29585858, 0.22897474, 0.14780825, 0.22426914, 0.94545348],
       [0.78368226, 0.59017478, 0.3192495 , 0.20861875, 0.41848843],
       [0.68824805, 0.35510959, 0.3635563 , 0.43537603, 0.94175561],
       [0.1240994 , 0.58545785, 0.11530023, 0.01579722, 0.60025849],
       [0.55809233, 0.82426048, 0.65244566, 0.27645865, 0.45587913]])

In [17]:
np.random.randn(5,5)

array([[ 0.27770764, -0.40476242,  0.0285432 , -1.43720345,  1.80396797],
       [-1.62444676,  1.90079135, -0.11155976, -0.35337533,  1.75838349],
       [-0.66261594, -0.33864735,  0.86190106, -0.45687715,  0.68666104],
       [-1.79142542,  0.5251685 ,  2.37808159,  0.14504286, -0.73504036],
       [-1.6570026 , -0.53003129,  0.40601401, -0.28354966, -1.50220453]])

In [19]:
np.random.randint(1,100,10)

array([96, 15, 18, 89, 12, 77, 67, 47, 96, 28])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
randarr = np.random.randint(0,50,10)

In [26]:
randarr

array([25, 34, 35, 27, 40,  3, 43, 43, 32, 31])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
randarr.max()

43

In [29]:
randarr.min()

3

In [30]:
randarr.argmax()

6

In [31]:
randarr.argmin()

5

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int32')